version: '3'
services:
  php:
    build: .
    ports:
      - 8080:80
    volumes:
       - ./:/var/www/html

    environment:
       - BBDD_USER=root
       - BBDD_PASSWORD=root
       - BBDD_HOST=mysql
       - BBDD_DATABASE=2daw
       - BBDD_HOST_PORT=3306

  mysql:
    image: mysql:5.7.28
    ports:
      - 1024:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=2daw
      - MYSQL_USER=ferni	
      - MYSQL_PASSWORD=1234567
    volumes:
      - ./mysql-data22:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
