version: '3'
services:
  php:
    build: .
    ports:
      - 8080:80
    volumes:
       - $HOME/kart:/var/www/html 
    environment:
      - BBDD_USER=usuario
      - BBDD_PASSWORD=password
      - BBDD_HOST=mysql
      - BBDD_DATABASE=2daw
      - BBDD_HOST_PORT=3306
    
  mysql:
    image: mysql:5.7.28
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - $HOME/kart-data:/var/lib/mysql
    #command: --init-file Productos.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql


